name: Build debug app APK

on:
  push:
    branches:
      - '**'
    pull_request:
      - main

jobs:

  apk-debug:
    name: Generate debug APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: 11
            distribution: 'adopt'
            
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build APK      
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Blueffruit Connect debug APK
          path: app/build/outputs/apk/debug/*.apk 
    